service: fetch-file-and-store-in-s3

frameworkVersion: '2'

custom:
  bucket: paul-tipper-sls-test-20210211

functions:
  save:
    handler: handler.save
    events:
      - s3:
          bucket: ${self:custom.bucket}
          # existing: true
    environment:
      BUCKET: ${self:custom.bucket}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  s3:
    bucketOne:
      name: ${self:custom.bucket}
  
resources:
  Resources:
    LoggingBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: LogDeliveryWrite
    Helper:
      Type: AWS::S3::Bucket
  extensions:
    S3BucketPaultipperslstest20210211:
      # Type: AWS::S3::Bucket
      Properties:
        # BucketName: paul-tipper-sls-test-20210211
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        AccelerateConfiguration:
          AccelerationStatus: Enabled
        VersioningConfiguration:
          Status: Enabled
        AccessControl: Private
        LoggingConfiguration:
          DestinationBucketName: !Ref LoggingBucket
          LogFilePrefix: testing-logs
        # IntelligentTieringConfiguration:
        #   Id: S3BucketPaultipperslstest20210211_Tier
        #   Status: Enabled
        #   Tierings: 
        #     - AccessTier: ARCHIVE_ACCESS
        #       Days: 120
        LifecycleConfiguration:
          Rules:
            - Id: GlacierRule
              Prefix: glacier
              Status: Enabled
              ExpirationInDays: 365
              Transitions:
                - TransitionInDays: 2
                  StorageClass: GLACIER
        AnalyticsConfigurations:
          - Id: AnalyticsConfigurationId
            StorageClassAnalysis:
              DataExport:
                Destination:
                  BucketArn: !GetAtt 
                    - Helper
                    - Arn
                  Format: CSV
                  Prefix: AnalyticsDestinationPrefix
                OutputSchemaVersion: V_1
            Prefix: AnalyticsConfigurationPrefix
            TagFilters:
              - Key: AnalyticsTagKey
                Value: AnalyticsTagValue
        InventoryConfigurations:
          - Id: InventoryConfigurationId
            Destination:
              BucketArn: !GetAtt 
                - Helper
                - Arn
              Format: CSV
              Prefix: InventoryDestinationPrefix
            Enabled: 'true'
            IncludedObjectVersions: Current
            Prefix: InventoryConfigurationPrefix
            ScheduleFrequency: Daily




